# Generated by Django 5.0.7 on 2024-08-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
