# Generated by Django 5.0.7 on 2024-08-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
