# Generated by Django 5.0.7 on 2024-08-16 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
