# Generated by Django 5.0.7 on 2024-08-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapp', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
