# Generated by Django 5.0.7 on 2024-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapp', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('stripe', 'Stripe'), ('wallet', 'Wallet')], max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
