# Generated by Django 5.0.7 on 2024-08-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapp', '0010_alter_paymentmethod_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
