# Generated by Django 5.0.7 on 2024-08-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapp', '0012_order_cancelled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled')], max_length=255),
        ),
    ]
