# Generated by Django 5.0.7 on 2024-08-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapp', '0013_alter_orderstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'razorpay'), ('wallet', 'Wallet')], max_length=255),
        ),
    ]
