# Generated by Django 5.0.7 on 2024-08-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutapp', '0014_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
