# Generated by Django 5.0.7 on 2024-07-18 11:47

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_category_is_deleted_category_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(null=True, validators=[adminapp.models.validate_positive]),
        ),
    ]
